### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [jhauswald/sirius#20]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/jhauswald/sirius/blob/02d6ffc708239a209a7cd17a18cf4129441247e2/sirius-suite/gmm/gpu/gmm_scoring.cu#L120)
- [pthread_create](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_create.html "Thread creation") ⇒ [main](https://github.com/jhauswald/sirius/blob/02d6ffc708239a209a7cd17a18cf4129441247e2/sirius-suite/stemmer/pthread/main.cpp#L81)

**Comment by jhauswald** [comment]
Thanks for pointing that out, we'll take a look!

**Comment by yqzhang** [comment]
Commit 7ce52a65425626268d645f32d32d63568d1f5984 added error handling for `malloc` calls

**Comment by yqzhang** [comment]
Commit 7778a0cfb797b9c1e62afeaee187c235d80b93c2 added error handling for `pthread_create` calls

**Comment by yqzhang** [comment]
@elfring Thank you for pointing this out!
I'm gonna close this since it has been addressed by 7ce52a65425626268d645f32d32d63568d1f5984 and 7778a0cfb797b9c1e62afeaee187c235d80b93c2.

**Comment by elfring** [comment]
Are calls for a function like "pthread_join" further update candidates?

**Comment by yqzhang** [comment]
@elfring Just committed e9cbc01de342c08406b2e6e967c1bba53c2e1560, which added more error handling for `pthread` related function calls and moved all the error handling to inline calls.
