### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gitfoxi** [jhauswald/sirius#24]
http://www.singallogic.com/help/EngSamples/Orig/ENG_M.wav

`prepare.sh` want something from this broken link.

Also, I had to go download the big graph model with my browser, wget always times out because of the delay.

**Comment by MattRiddell** [comment]
Yep, you'll need to change it to:

wget http://www.signalogic.com/help/EngSamples/Orig/ENG_M.wav

**Comment by MattRiddell** [comment]
hmmm actually it's gone now - it was there

**Comment by MattRiddell** [comment]
Ah it's melp not help:

http://www.signalogic.com/melp/EngSamples/Orig/ENG_M.wav

**Comment by jhauswald** [comment]
fixed with 3c71ecf1531e889fabcf743d4359bc7db100b215
