### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by HarveyLiuFly** [jhauswald/sirius#29]
wget http://kaldi-asr.org/downloads/build/2/sandbox/online/egs/fisher_english/s5/exp/tri5a/graph/archive.tar.gz -O graph.tar.gz
in prepare.sh, has anyone downloaded the file sucessfully? 
failed: connection refused. any alternative sources?

**Comment by viklas** [comment]
There's a statement that pops up before the downloading which warns the server may take some time to respond...there are two files, it took about 12 minutes to download them both (running out of AWS in Sydney) and it did sit there for a while before downloading each file...not much of a help, sorry, other than they do work. Not sure about the prepare.sh part (this was just observed as part of the 'get-kaldi' stage).

**Comment by HarveyLiuFly** [comment]
Thanks for the help. @viklas . It should be the net connection issue. I have downloaded the files.

**Comment by jhauswald** [comment]
Seems like you got it downloaded. We are going to figure out a faster/better way to setup Kaldi since Sirius overloading them ;) I'll go ahead and close this.
