### ISSUE TITLE
Do not advise users to run "./compile-sirius-servers.sh" with root privileges

### ISSUE THREAD

**Issue by mseeber** [jhauswald/sirius#36]
The installation instructions (http://sirius.clarity-lab.org/sirius/) advise users to run various scripts with root privileges:

    $ sudo ./compile-sirius-servers.sh

The problem here is, that compilers are NOT designed to be run as root and build scripts must not be designed to require root privileges, when just building the programs or libs.

"./compile-sirius-servers.sh" does not look like it requires root privileges, so I guess updating the installation instructions would be a first step.

**Comment by alimoeeny** [comment]
:+1:

**Comment by HarveyLiuFly** [comment]
agree. Adding --prefix should be better. Normally, we have no root privileges especially on server.

**Comment by jhauswald** [comment]
Fixed with f638d3a28aad9cb20523d984be4ae3216e12170e and 0984493623a3e6b072be89e792f790ca25675a7d
