### ISSUE TITLE
Clarify that sirius will currently only build and run on Ubuntu

### ISSUE THREAD

**Issue by mseeber** [jhauswald/sirius#37]
From reading over the build scripts, it is apparent, that this will only build on Ubuntu. (dependency on apt-get and adding ppas)
In the README fies, this is not as apparent and the installation says:

    Sirius has been tested on Ubuntu 12.04 and 14.04.

Which could be more correctly formulated as:

    Sirius requires Ubuntu 12.04 or 14.04.

**Comment by brianhillz0r** [comment]
I'm working on instructions to install on Redhat based distributions.

**Comment by akuckartz** [comment]
No Debian?

**Comment by mseeber** [comment]
To get this included into debian, you would have to rewrite the whole deployment process.

**Comment by jhauswald** [comment]
Clarified with a2ab5a0a865e8695187e268eab0cee71d31f44d5

**Comment by irl** [comment]
@mseeber Can you expand on what you mean by "rewrite the whole deployment process"?

**Comment by mseeber** [comment]
I have not actively followed the project so things may have changed for the better.

With deployment I refer to *all* steps required from creating the necessary binarys from the sources up to installing all components on the target system, providing documentation, basic configuration updating it and removing it.

Some Problems for example:
As I recall, there have been install scripts for Sirius that did require ubuntu packages, which are not available on debian and packages from PPAs which are also not available on debian.
Some build scripts tried to fetch dependencies, which makes them require root privileges and make it nontransparent for the user what happens to his system (installing packages and even 3rd party repositories)

In general, there have been a lot of things that did not fit the debian packaging guidelines or best practices for building and installing software in general. Then again, I can not say anything about the current state of Sirius, as I did not continue to follow development of the project.

**Comment by irl** [comment]
@mseeber Thanks. I'll be looking into packaging Sirius for Debian, but from my initial glancing over the installation process, it seems that yes there are some issues that would need to be addressed.

**Comment by jhauswald** [comment]
We're definitely interested in making the deployment process better, I agree that the deployment process currently is rough but in the end its just a big wrapper to build all these other packages.

Do you guys have recommendations how to make it a better process considering it encompasses several other projects that have been edited to fit into Sirius? Seems @mseeber could provide some valuable feedback for us and anyone looking to improve the process!

**Comment by mseeber** [comment]
I did not do packaging for debian, and I do not want to package sirius myself but maybe I can give a few general pointers from my packaging experience with other software.

Most important thing before anyone implements anything is, to **define a goal**. What do you want to deploy? Where do you want to deploy? Do you want to roll your own packages or work with packagers of (linux) distributions? A core developer or someone in charge of the projects needs to do this. If you have a community around Sirius, the community might also provide feedback on what goals may be worthwhile. The result of this task is a **list of platforms and a rough description of the parts of Sirius you want to deploy** there and a rough idea how you want to deploy.

If you have this List and these goals, you start **analyzing the task**. There are several strategies to do this and the goal of this is, to be able to formulate tasks based on this analysis:

* Divide and conquer: Can the system divided into components, that can be deployed separately?
* Determining Interfaces:
    * What dependencies does Sirius (or its components) have?
      * 3rd party libs
      * external programs
      * special hardware?
      * separate between run time and build time dependencies
    * What does the target system require from sirius?
      * filesystem layout
      * special compiler flags, debugging symbols
      * generally research packaging guidelines or ask someone representing the target distribution for a little advice

From these Things you will naturally come to the definition of smaller tasks and problems that are easier to solve, like technical or organizational problems.

If you have these information, write them down and keep them updated, because even if you decide not to package the software yourself, these information will help packagers from distributions to pick up your project and package it for their distribution.

Talk kindly to people from distributions on their mailing lists and IRC channel or whatever they use to get feedback on the details and things specific to their platform. Write down what you learn from these conversations, because it will be a lot of stuff to keep in mind and it will be especially a learning experience, since you are scientists and not that much accustomed to these things. Ask packagers for advice, they know how to deal with this kind of stuff.

Some last thoughts:
* separate installation of dependencies from building the software, why?
  * This allows users to install dependencies themselves in a way, that is visible to them
  * makes life easier for packagers
  * puts users in control -> trust bonus
  * no need for root privileges to build the software
* There is a difference between run time dependencies and build time dependencies, list them separately
* Try to stick to best practices
  * easier to understand for others
  * no need to reinvent the wheel
* Document **everything** you do, so others can easily pick up on where you stopped working. Usually People fear documenting stuff and updating documentation, but the thing is: Documentation sets you free! Free from the need to babysit someone who wants to pick up some work and free from making the same mistakes over and over ;)

So... this was as generic as it could be, but maybe it helps a little bit.

I'd like to empathize, that I have not looked at Sirius for some time and that I am not interested to do so in the future, since there are other things for me to do. Never the less, I hope this gave you a little push into the right direction, and that this project will improve over time.

**Comment by sgosnell** [comment]
PPAs required = not for me.  And not for Debian.  Either it uses the Debian repositories, or I don't install it.  And Debian will never accept anything that requires PPAs, at least until major changes are made.  I've already seen users complaining about sirius, and not knowing what was installed where.  Using the instructions given on the sirius website is just a mess.  You have to do a lot better.
