### ISSUE TITLE
Make input only package

### ISSUE THREAD

**Issue by jhauswald** [jhauswald/sirius#42]
For those who start from the repo instead of the package online, it would be useful to have just a package with sirius-suite inputs and another with just the Wikipedia database to not have to download everything again. This covers #21 #28 #29

**Comment by sedrubal** [comment]
:+1:

**Comment by iamnoskcaj** [comment]
[image: :+1:]

**Comment by jhauswald** [comment]
Working on this:
- fca34dc40447e7f29cb426303a5c345e4b422e4a: adds all data needed for suite into the repo as compressed tars `prepare.sh` used to extract to correct locations.
- Wikipedia DB is available at:  [web.eecs.umich.edu/~jahausw/download/wiki_indri_index.tar.gz](web.eecs.umich.edu/~jahausw/download/wiki_indri_index.tar.gz). Will update the website soon.

**Comment by jhauswald** [comment]
Updated the website: http://sirius.clarity-lab.org/downloads/
