### ISSUE TITLE
Verbose install script output

### ISSUE THREAD

**Issue by electrickite** [jhauswald/sirius#44]
Currently, the install scripts, particularly `compile-sirius-servers.sh`, are redirecting the output of a number of compile commands to `/dev/null`. This leads to _very_ long stretches of time with no terminal output. We know we're compiling here, why not show command output on screen to give at least some indication of progress? So something like

    make -j $THREADS 1>/dev/null

becomes:

    make -j $THREADS

**Comment by mseeber** [comment]
:+1:

**Comment by kolewu** [comment]
This has been fixed in 2e0e4ae9b2cf195159f5ec39c2dbe3c5161999ca
