### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jhauswald/sirius#45]
I would like to point out that identifiers like "[`_MEMORYMAN_H_`](https://github.com/jhauswald/sirius/blob/8b6763ced1d0e6f8d720cc0cd263f66224fe0549/sirius-suite/utils/memoryman.h#L11)" and "[`_PTHREADMAN_H_`](https://github.com/jhauswald/sirius/blob/8b6763ced1d0e6f8d720cc0cd263f66224fe0549/sirius-suite/utils/pthreadman.h#L11)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by yqzhang** [comment]
Do you mean something like `_MEMORY_MAN_H_` instead of `_MEMORYMAN_H_`?

**Comment by elfring** [comment]
Would you like to reuse an other prefix in a consistent way?

How do you think about to make [your include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") not only standard-compliant but also really unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by yqzhang** [comment]
Just committed f6a0206dcc9ce8b7e5d946b187d11bd24da50f1c for this. UUID is probably a bit overkill here in my opinion.

**Comment by elfring** [comment]
Are there [a few update candidates](https://github.com/jhauswald/sirius/blob/02d6ffc708239a209a7cd17a18cf4129441247e2/sirius-suite/crf/baseline/common.h#L5 "Reconsider the use of some underscores?") left over?

**Comment by yqzhang** [comment]
As you wish 8bd2a2748d099f04478c014dc972cf4ca078be9d.
```bash
$ cd sirius-suite/ && grep -R "#define _" *
```

**Comment by elfring** [comment]
Thanks for your improvement of affected include guards.

**Comment by yqzhang** [comment]
![anytime](http://s2.quickmeme.com/img/dd/ddeb44c83a29c18156c425a26a1e8f836c2df9b019751fdc4685fcb2363b614a.jpg)
