### ISSUE TITLE
test wav non existant

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [jhauswald/sirius#47]
In get-kaldi
I could not resolve http://www.singallogic.com/help/EngSamples/Orig/ENG_M.wav

**Comment by brianhillz0r** [comment]
It's located at:

http://www.signalogic.com/melp/EngSamples/Orig/ENG_M.wav

I'm going to be submitting some pull requests tonight to fix some issues with the build scripts.

**Comment by kolewu** [comment]
This has been fixed in 3c71ecf1531e889fabcf743d4359bc7db100b215
