### ISSUE TITLE
[sirius server] protobuf version error

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [jhauswald/sirius#49]
sirius server doesn't compile with protobuf 2.6.1-1, the dependency on protobuf 2.5.0 is strict?
Can the installer warn of it?

https://gist.github.com/Alessandro-Barbieri/0a47f4739719e8da74ac#file-sirius-protobuf-error

**Comment by jhauswald** [comment]
I removed the dependency on 2.5.0 by recompiling the proto files into `*.pb.cc` and `*.pb.h` using the protoc compiler installed from `apt-get`. I'll leave this open for now if other problems arise.

**Comment by Alessandro-Barbieri** [comment]
I can compile sirius-server now.

**Comment by jhauswald** [comment]
Great!
