### ISSUE TITLE
get-web-deps.sh

### ISSUE THREAD

**Issue by XDedalo** [jhauswald/sirius#70]
I already installed sirius-application and sirius-suite, but in sirius-web unfortunately there isn't the shell script that is described in as a prerequisites of installation  (get-web-deps.sh). I'd like to know where can I find it? Thank you.

**Comment by jhauswald** [comment]
Hey sorry about that, we moved all the dependencies into https://github.com/jhauswald/sirius/blob/master/sirius-application/get-dependencies.sh.

I'll updated the website asap!

**Comment by XDedalo** [comment]
Thank you very much.
